# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.13"
  jobs:
    # https://github.com/readthedocs/readthedocs.org/issues/10715
    post_checkout:
      - git fetch --tags
    pre_install:
      - git update-index --assume-unchanged environment.yml docs/source/conf.py

# Install the package before building so we can get the version
python:
  install:
    - method: pip
      path: .

# Build documentation in the "docs/" directory with Sphinx
sphinx:
   configuration: docs/source/conf.py


