name: Build and test Python packages

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  build-distribution:
    name: Build distribution
    runs-on: ubuntu-slim
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
        ref: ${{ inputs.ref }}

    - uses: actions/setup-python@v6
      with:
        python-version: "3.x"

    - name: Install build and twine
      run: python3 -m pip install build twine --user

    - name: Build packages
      run: python3 -m build

    - name: Test packages
      run: python3 -m twine check dist/*

    - name: Store packages
      uses: actions/upload-artifact@v7
      with:
        name: python-package-distributions
        path: dist/

