name: Do release

on:
  pull_request:
    branches: main
    types: [closed]

jobs:
  describe_release:
    name: Perform all actions necessary to release the package
    runs-on: ubuntu-slim
    if: ${{ github.event.pull_request.merged }}
    steps:
      - name: Test variables
        run: |
          echo "${{ github.event.pull_request.title }}"
          echo "${{ github.actor }}"
          echo "${{ github.event.pull_request.merge_commit_sha }}"

      - name: Determine the release version from the PR title
        run: |
          echo "${{ github.event.pull_request.title }}"
          if echo "${{ github.event.pull_request.title }}" | grep -q 'Release \([0-9]\+\.[0-9]\+\.[0-9]\+\)' ; then
              echo '${{ github.event.pull_request.title }}' | sed -e 's/Release \([0-9]\+\.[0-9]\+\.[0-9]\+\)/release_version=\1/') >> $GITHUB_ENV
          fi

      - name: Check out the repository
        uses: actions/checkout@v6

      - name: Tag the released version with a version tag
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git tag -a -m "Release ${release_version}" "v${release_version}" "${{ github.event.pull_request.merge_commit_sha }}"
          git push --tags
