name: Do release

on:
  pull_request:
    branches: main
    types: [closed]

jobs:
  get_description:
    name: Get version and description from the CHANGELOG.md and overview.txt files
    uses: $/.github/workflows/create_release_description.yml

  do_release:
    name: Release the package
    needs: [get_description]
    runs-on: ubuntu-slim
    if: ${{ github.event.pull_request.merged }}
    permissions:
      contents: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 2
          ssh-key: ${{ secrets.RELEASE_KEY }}

      - name: Tag the released version with a version tag
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git tag -a -m "Release ${{ needs.get_description.outputs.version }}" "v${{ needs.get_description.outputs.version }}" "${{ github.event.pull_request.merge_commit_sha }}"
          git push --tags

      - name: Make a GitHub release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ needs.get_description.outputs.version }}
          name: Sanotehu ${{ needs.get_description.outputs.version }}
          body: ${{ fromJSON(needs.get_description.outputs.description) }}

      - name: Release to TestPyPI
        uses: $/.github/workflows/release_to_pypi.yml
        with:
          tag: v${{ needs.get_description.outputs.version }}

      - name: Merge main back into develop
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git fetch --all
          git switch develop
          git merge --no-ff -X theirs main
          git push
