name: Prepare release

on:
  pull_request:
    branches: main

jobs:
  describe_release:
    name: Describe release for an admin to check that all is well
    runs-on: ubuntu-slim
    steps:
      - name: Write a basic comment
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Hello world! :wave:
