name: Prepare release

on:
  pull_request:
    branches: main
    types:
      - opened
      - synchronize
      - edited
      - reopened

jobs:
  parse-title:
    name: Get version from the release PR's title
    uses: $/.github/workflows/parse_title.yml
    with:
      title: ${{ github.event.pull_request.title }}

  get-description:
    name: Get version and description from the CHANGELOG.md and overview.txt files
    uses: $/.github/workflows/create_release_description.yml

  report_error:
    name: Report error if the versions in the title and in the CHANGELOG don't match
    needs:
      - parse-title
      - get-description
    runs-on: ubuntu-slim
    if: ${{ needs.parse-title.outputs.version != needs.get-description.outputs.version }}
    permissions:
      pull-requests: write
    steps:
      - name: Post an error message
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: >
            **ERROR** This PR is for release ${{ needs.parse-title.outputs.version }}
            but the most recent version in CHANGELOG.md is
            ${{ needs.get-description.outputs.version }}. Please ensure that the title
            of this PR matches `Release x.y.z` exactly, and that the topmost `##` entry
            in CHANGELOG.md is for the exact same version.
      - name: Fail the check
        run: exit 1

  describe_release:
    name: Describe release for an admin to check that all is well
    needs:
      - parse-title
      - get-description
    runs-on: ubuntu-slim
    if: ${{ needs.parse-title.outputs.version == needs.get-description.outputs.version }}
    permissions:
      pull-requests: write
    steps:
      - name: Post preview of the release description
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Here's a preview of the release description if you merge this PR:

            ${{ fromJSON(needs.get-description.outputs.description) }}

  build-python-packages:
    name: Build and test Python packages
    needs: [get-description]
    uses: $/.github/workflows/build_test_python_packages.yml
    with:
      ref: ${{ github.event.pull_request.head.ref }}

