name: Release packages on PyPI

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  build_distribution:
    name: Build distribution
    runs-on: ubuntu-slim
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
        ref: ${{ inputs.tag }}

    - uses: actions/setup-python@v6
      with:
        python-version: "3.x"

    - name: Install build
      run: python3 -m pip install build --user

    - name: Build packages
      run: python3 -m build

    - name: Store packages
      uses: actions/upload-artifact@v5
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: Publish to TestPyPI
    needs:
    - build
    runs-on: ubuntu-slim
    environment:
      name: testpypi
      url: https://test.pypi.org/p/sanotehu
    permissions:
      id-token: write
    steps:
    - name: Download packages
      uses: actions/download-artifact@v6
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish packages to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

